"use client"

import { useState, useEffect } from "react"
import { useParams, useRouter } from "next/navigation"
import { createClient } from "@/lib/supabase/client"
import { Button } from "@/components/ui/button"

export default function WebsitePreviewPage() {
    const params = useParams()
    const router = useRouter()
    const submissionId = params.id as string

    const [loading, setLoading] = useState(true)
    const [websiteCode, setWebsiteCode] = useState<string | null>(null)
    const [error, setError] = useState<string | null>(null)

    useEffect(() => {
        loadWebsite()
    }, [submissionId])

    const loadWebsite = async () => {
        try {
            const supabase = createClient()
            const { data: { user } } = await supabase.auth.getUser()

            if (!user) {
                router.push('/login')
                return
            }

            const { data: submission, error: fetchError } = await supabase
                .from('submissions')
                .select('website_code, creator_id')
                .eq('id', submissionId)
                .single()

            if (fetchError) throw fetchError

            // Check if user owns this submission
            if (submission.creator_id !== user.id) {
                setError('You do not have permission to view this website')
                return
            }

            if (!submission.website_code) {
                setError('Website has not been generated yet')
                return
            }

            setWebsiteCode(submission.website_code)
        } catch (err: any) {
            console.error('Error loading website:', err)
            setError(err.message || 'Failed to load website')
        } finally {
            setLoading(false)
        }
    }

    if (loading) {
        return (
            <div className="min-h-screen bg-gray-50 flex items-center justify-center">
                <div className="text-center">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-green-500 mx-auto mb-4"></div>
                    <p className="text-gray-600">Loading website preview...</p>
                </div>
            </div>
        )
    }

    if (error) {
        return (
            <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
                <div className="bg-white rounded-xl p-8 max-w-md w-full text-center">
                    <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg className="w-8 h-8 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </div>
                    <h2 className="text-xl font-bold text-gray-900 mb-2">Error</h2>
                    <p className="text-gray-600 mb-6">{error}</p>
                    <Button onClick={() => router.back()}>Go Back</Button>
                </div>
            </div>
        )
    }

    return (
        <div className="min-h-screen bg-white">
            {/* Preview Controls */}
            <div className="fixed top-0 left-0 right-0 bg-gray-900 text-white px-4 py-3 z-50 flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Button
                        onClick={() => router.back()}
                        variant="outline"
                        size="sm"
                        className="bg-white/10 border-white/20 text-white hover:bg-white/20"
                    >
                        <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                        </svg>
                        Back
                    </Button>
                    <span className="text-sm">Website Preview</span>
                </div>
                <div className="flex items-center gap-2">
                    <span className="text-xs text-gray-400">Generated by Groq AI</span>
                </div>
            </div>

            {/* Website Content */}
            <div className="pt-14">
                <iframe
                    srcDoc={websiteCode || ''}
                    className="w-full h-[calc(100vh-3.5rem)] border-0"
                    title="Website Preview"
                    sandbox="allow-scripts allow-same-origin"
                />
            </div>
        </div>
    )
}
